import type { LiteralUnion, Prettify } from "@padosoft/utilities";
import type { Client, ClientOptions, Middleware } from "openapi-fetch";
import createClient from "openapi-fetch";
import type { MediaType } from "openapi-typescript-helpers";
import type {
	ClientMethodReturn,
	ClientMiddleware,
	ClientMiddlewareFunctionParameters,
	ClientMiddlewareType,
	CreateClientMiddlewareOptions,
	CustomMiddlewareBaseParamsMap,
	CustomMiddlewareCallbackParams,
	CustomMiddlewareFunction,
	CustomMiddlewareKeys,
	OnResponseErrorMiddlewareFunction,
	OpenApiPaths,
	ReturnTypeFromClientMethod,
	StoredMiddleware,
} from "../types/base";
import {
	extractErrorCause,
	isOpenApiFetchClient,
	safeJSONStringify,
} from "./utils";

/**
 * Type-safe wrapper around an openapi-fetch {@link Client}.
 *
 * Provides middleware registration (native openapi-fetch hooks and custom ones
 * such as `onResponseError`), cloning, and automatic error handling via
 * {@link wrapFetchCall}.
 *
 * @typeParam Paths - OpenAPI path definitions generated by openapi-typescript.
 */
export class OpenApiClient<Paths extends OpenApiPaths> {
	/** The underlying openapi-fetch client instance. */
	protected client: Client<Paths, MediaType>;
	/** Registry of named middlewares currently attached to this client. */
	protected middlewares: Map<string, StoredMiddleware<typeof this>> = new Map();
	/** Middleware types that map directly to native openapi-fetch hooks. */
	protected static INTERNAL_MIDDLEWARES: LiteralUnion<
		keyof Middleware,
		string
	>[] = ["onRequest", "onResponse", "onError"];

	/** The {@link ClientOptions} used to create the current client, if any. */
	protected options?: ClientOptions | undefined;

	/**
	 * @internal Creates a new openapi-fetch client instance
	 * @param options Client options
	 * @returns api client
	 */
	static createClient<Paths extends OpenApiPaths>(
		options?: ClientOptions,
	): Client<Paths> {
		return createClient<Paths, MediaType>(options);
	}

	/**
	 * Creates a typed middleware descriptor that can be passed to {@link use}.
	 *
	 * If `name` is omitted the middleware `type` is used as its name,
	 * meaning only one middleware per type can be registered at a time.
	 *
	 * @typeParam K - The middleware hook type (e.g. `"onRequest"`, `"onResponse"`).
	 * @typeParam N - Optional custom name for the middleware.
	 * @typeParam C - The concrete {@link OpenApiClient} subclass the middleware targets.
	 * @param options - Middleware configuration including type, name, and callback.
	 * @returns A resolved middleware descriptor with a guaranteed `name`.
	 *
	 * @example
	 * ```ts
	 * const authMiddleware = OpenApiClient.createMiddleware({
	 *   name: "auth",
	 *   type: "onRequest",
	 *   middleware: async ({ request }) => {
	 *     request.headers.set("Authorization", "Bearer my-token");
	 *     return request;
	 *   },
	 * });
	 *
	 * client.use(authMiddleware);
	 * ```
	 *
	 * @example
	 * ```ts
	 * // Without an explicit name (defaults to the type):
	 * const errorLogger = OpenApiClient.createMiddleware({
	 *   type: "onError",
	 *   middleware: async ({ error }) => {
	 *     console.error("Fetch failed:", error);
	 *     throw error;
	 *   },
	 * });
	 * ```
	 */
	static createMiddleware<
		K extends ClientMiddlewareType,
		N extends string,
		C extends OpenApiClient<OpenApiPaths> = OpenApiClient<OpenApiPaths>,
	>(
		options: CreateClientMiddlewareOptions<K, N, C>,
	): Omit<CreateClientMiddlewareOptions<K, N, C>, "name"> & {
		name: N | (N extends undefined ? K : N);
	} {
		return {
			name: (options.name || options.type) as N extends undefined ? K : N,
			...options,
		};
	}

	/**
	 * Replaces the underlying client with a new one built from the given
	 * options, or swaps in an existing {@link Client} instance directly.
	 *
	 * @param optionsOrClient - Either {@link ClientOptions} to create a new
	 *   client, or an already-instantiated openapi-fetch {@link Client}.
	 *   When `undefined`, the call is a no-op.
	 * @returns `this` for chaining.
	 *
	 * @example // With client options:
	 * ```ts
	 * client.setClient({ baseUrl: "https://api.example.com/v2" });
	 * ```
	 *
	 * @example // With an existing openapi-fetch client:
	 * ```ts
	 * import createClient from "openapi-fetch";
	 *
	 * const raw = createClient<Paths>({ baseUrl: "https://api.example.com" });
	 * client.setClient(raw);
	 * ```
	 */
	setClient(optionsOrClient?: ClientOptions | Client<Paths, MediaType>): this {
		if (!optionsOrClient) {
			return this;
		}

		if (isOpenApiFetchClient<Paths>(optionsOrClient)) {
			this.client = optionsOrClient;
			return this;
		}

		this.client = OpenApiClient.createClient<Paths>(optionsOrClient);
		this.options = optionsOrClient;

		return this;
	}

	/**
	 * @param optionsOrClient - {@link ClientOptions} to configure a new client,
	 *   or an existing openapi-fetch {@link Client} to wrap.
	 *
	 * @example
	 * ```ts
	 * const client = new OpenApiClient<Paths>({
	 *   baseUrl: "https://api.example.com",
	 * });
	 * ```
	 */
	constructor(optionsOrClient?: ClientOptions | Client<Paths, MediaType>) {
		this.client = OpenApiClient.createClient<Paths>();
		this.setClient(optionsOrClient);
	}

	/**
	 * Creates a shallow clone of this client with all registered middlewares.
	 *
	 * The clone receives a fresh openapi-fetch client whose options are
	 * merged from the original options and the provided overrides.
	 *
	 * @param options - Optional {@link ClientOptions} overrides for the clone.
	 * @returns A new {@link OpenApiClient} instance.
	 *
	 * @example
	 * ```ts
	 * const v2Client = client.clone({
	 *   baseUrl: "https://api.example.com/v2",
	 * });
	 * ```
	 */
	clone(options?: ClientOptions): OpenApiClient<Paths> {
		const newClient = OpenApiClient.createClient<Paths>({
			...this.options,
			...options,
		});

		const cloned = new OpenApiClient<Paths>(newClient) as this;

		for (const middleware of this.middlewares.values()) {
			cloned.use(middleware);
		}

		return cloned;
	}

	/** The underlying openapi-fetch client (read-only). */
	get instance(): Readonly<Client<Paths, MediaType>> {
		return this.client;
	}

	/** The {@link ClientOptions} used to build the client, if any (read-only). */
	get configuration(): Readonly<ClientOptions | undefined> {
		return this.options;
	}

	/**
	 * Builds a standardised `Error` from an HTTP status code and response details.
	 *
	 * @param status - The HTTP status code.
	 * @param details - Arbitrary error payload; a `cause` property is extracted
	 *   and forwarded as the `Error.cause`.
	 * @returns An `Error` whose message includes the status and a JSON
	 *   representation of the remaining details.
	 */
	protected createApiError(status: number, details: unknown): Error {
		const { cause, rest } = extractErrorCause(details);

		const error = new Error(
			`API Error ${status}: ${safeJSONStringify(rest)}`,
			cause !== undefined ? { cause } : undefined,
		);
		return error;
	}

	/**
	 * Wraps a middleware callback so that the `client` reference is injected
	 * into its options parameter, making it compatible with the native
	 * openapi-fetch {@link Middleware} signature.
	 */
	private addClientToMiddleware<K extends keyof Middleware>(
		middleware: (
			options: ClientMiddlewareFunctionParameters<K, this>,
		) => ReturnType<NonNullable<Middleware[K]>>,
	): NonNullable<Middleware[K]> {
		//@ts-expect-error - Generic type mismatch when wrapping middleware, but works at runtime
		return (o: Parameters<NonNullable<Middleware[K]>>[0]) => {
			const options: ClientMiddlewareFunctionParameters<K, this> = {
				...o,
				client: this,
			} as const;

			return middleware(options);
		};
	}

	/**
	 * Registers a middleware on this client.
	 *
	 * If the middleware type corresponds to a native openapi-fetch hook
	 * (`onRequest`, `onResponse`, `onError`) it is forwarded to the
	 * underlying client; otherwise it is stored for manual invocation
	 * via {@link executeMiddlewaresOfType}.
	 *
	 * @param middleware - The middleware descriptor (created via
	 *   {@link createMiddleware} or manually).
	 * @returns `this` for chaining.
	 *
	 * @example
	 * ```ts
	 * const logging = OpenApiClient.createMiddleware({
	 *   name: "request-logger",
	 *   type: "onRequest",
	 *   middleware: async ({ request }) => {
	 *     console.log(`${request.method} ${request.url}`);
	 *     return request;
	 *   },
	 * });
	 *
	 * client.use(logging);
	 * ```
	 */
	use<K extends ClientMiddlewareType, N extends string>(
		middleware: ClientMiddleware<K, N, this>,
	): this {
		this.middlewares.set(middleware.name, middleware);

		if (!OpenApiClient.INTERNAL_MIDDLEWARES.includes(middleware.type)) {
			return this;
		}

		const middlewareObj = {
			[middleware.type]: (
				this.addClientToMiddleware as (m: unknown) => unknown
			)(middleware.middleware),
		} satisfies Partial<Middleware>;
		this.client.use(middlewareObj as Middleware);

		return this;
	}

	/**
	 * Removes a previously registered middleware by name.
	 *
	 * For native openapi-fetch hooks the middleware is also ejected from
	 * the underlying client.
	 *
	 * @param name - The name the middleware was registered with.
	 * @returns `this` for chaining.
	 *
	 * @example
	 * ```ts
	 * client.use(authMiddleware);
	 * // later…
	 * client.eject(authMiddleware.name);
	 * ```
	 */
	eject<N extends string>(name: N): this {
		const middleware = this.middlewares.get(name);
		if (!middleware) return this;

		this.middlewares.delete(name);

		if (!OpenApiClient.INTERNAL_MIDDLEWARES.includes(middleware.type)) {
			return this;
		}

		const middlewareObj = {
			[middleware.type]: middleware.middleware,
		} satisfies Partial<Middleware>;
		this.client.eject(middlewareObj as Middleware);

		return this;
	}

	/**
	 * Shorthand to register an `onError` middleware.
	 *
	 * Accepts either a bare callback or a full {@link ClientMiddleware}
	 * descriptor.
	 *
	 * @param middleware - The error handler callback or descriptor.
	 * @returns `this` for chaining.
	 *
	 * @example
	 * ```ts
	 * client.onError(async ({ error }) => {
	 *   console.error("Network error:", error);
	 *   throw error;
	 * });
	 * ```
	 */
	onError(
		middleware:
			| CustomMiddlewareFunction<"onError", this>
			| ClientMiddleware<"onError", string, this>,
	): this {
		if ("middleware" in middleware) {
			return this.use(middleware);
		}

		return this.use({
			name: "onError",
			type: "onError",
			middleware: this.addClientToMiddleware(middleware),
		});
	}

	/**
	 * Shorthand to register an `onRequest` middleware.
	 *
	 * Accepts either a bare callback or a full {@link ClientMiddleware}
	 * descriptor.
	 *
	 * @param middleware - The request interceptor callback or descriptor.
	 * @returns `this` for chaining.
	 *
	 * @example
	 * ```ts
	 * client.onRequest(async ({ request }) => {
	 *   request.headers.set("X-Custom-Header", "value");
	 *   return request;
	 * });
	 * ```
	 */
	onRequest(
		middleware:
			| CustomMiddlewareFunction<"onRequest", this>
			| ClientMiddleware<"onRequest", string, this>,
	): this {
		if ("middleware" in middleware) {
			return this.use(middleware);
		}

		return this.use({
			name: "onRequest",
			type: "onRequest",
			middleware: this.addClientToMiddleware(middleware),
		});
	}

	/**
	 * Shorthand to register an `onResponse` middleware.
	 *
	 * Accepts either a bare callback or a full {@link ClientMiddleware}
	 * descriptor.
	 *
	 * @param middleware - The response interceptor callback or descriptor.
	 * @returns `this` for chaining.
	 *
	 * @example
	 * ```ts
	 * client.onResponse(async ({ response }) => {
	 *   console.log("Status:", response.status);
	 *   return response;
	 * });
	 * ```
	 */
	onResponse(
		middleware:
			| CustomMiddlewareFunction<"onResponse", this>
			| ClientMiddleware<"onResponse", string, this>,
	): this {
		if ("middleware" in middleware) {
			return this.use(middleware);
		}

		return this.use({
			name: "onResponse",
			type: "onResponse",
			middleware: this.addClientToMiddleware(middleware),
		});
	}

	/**
	 * Runs every registered middleware whose `type` matches the given key.
	 *
	 * Each middleware receives the provided `params` augmented with a
	 * `client` reference. Errors thrown by individual middlewares are
	 * silently caught so that one failing handler does not prevent the
	 * remaining ones from executing.
	 *
	 * @typeParam K - The custom middleware type to execute.
	 * @param type - The middleware type key.
	 * @param params - Base parameters forwarded to each middleware.
	 * @param executeCallback - Optional override for how each middleware is
	 *   invoked; defaults to calling `middleware.middleware(options)`.
	 * @returns `this` for chaining.
	 */
	protected async executeMiddlewaresOfType<K extends CustomMiddlewareKeys>(
		type: K,
		params: CustomMiddlewareBaseParamsMap[K],
		executeCallback: (
			middleware: ClientMiddleware<K, string, this>,
			options: CustomMiddlewareCallbackParams<K, this>,
		) => Promise<void> = async (m, p) => {
			const middleware = m as ClientMiddleware<
				CustomMiddlewareKeys,
				string,
				this
			>;
			return await middleware.middleware(p);
		},
	): Promise<this> {
		for (const middleware of this.middlewares.values()) {
			if (middleware.type !== type) continue;

			const options = {
				...params,
				client: this,
			} satisfies CustomMiddlewareCallbackParams<K, this>;

			try {
				await executeCallback(
					middleware as ClientMiddleware<K, string, this>,
					options,
				);
			} catch {}
		}

		return this;
	}

	/**
	 * Shorthand to register an `onResponseError` middleware.
	 *
	 * This is a custom (non-native) middleware type invoked by
	 * {@link wrapFetchCall} whenever a response indicates an error.
	 *
	 * @param middleware - The error handler callback or descriptor.
	 * @returns `this` for chaining.
	 *
	 * @example
	 * ```ts
	 * client.onResponseError(async ({ response, error }) => {
	 *   if (response.status === 401) {
	 *     await refreshToken();
	 *   }
	 * });
	 * ```
	 */
	onResponseError(
		middleware:
			| OnResponseErrorMiddlewareFunction<this>
			| ClientMiddleware<"onResponseError", string, this>,
	): this {
		if ("middleware" in middleware) {
			return this.use(middleware);
		}

		return this.use({
			name: "onResponseError",
			type: "onResponseError",
			middleware,
		});
	}

	/**
	 * Unwraps an openapi-fetch call, returning the `data` on success or
	 * throwing a structured {@link Error} on failure.
	 *
	 * - `2xx` with a body: returns `data`.
	 * - `204 No Content`: returns `undefined`.
	 * - Any other status: builds an error via {@link createApiError},
	 *   fires `onResponseError` middlewares, and throws.
	 *
	 * @typeParam R - The raw return type of the openapi-fetch method.
	 * @param promise - The pending openapi-fetch call.
	 * @returns The response data (or `undefined` for 204).
	 * @throws {Error} When the response represents an error.
	 */
	protected async wrapFetchCall<R extends ClientMethodReturn>(
		promise: Promise<R>,
	): Promise<Prettify<ReturnTypeFromClientMethod<R>>> {
		const res = await promise;

		if (res.data) {
			return res.data;
		}

		// Gestisce 204 No Content (response senza body)
		if (res.response.status === 204) {
			return undefined;
		}

		if (!res.error?.message) {
			const error = this.createApiError(res.response.status, {
				cause: res.response,
				code: "UNKNOWN",
			});

			this.executeMiddlewaresOfType("onResponseError", {
				response: res.response,
				error,
			});

			throw error;
		}

		const error = this.createApiError(res.response.status, res.error);
		this.executeMiddlewaresOfType("onResponseError", {
			response: res.response,
			error,
		});

		throw error;
	}
}
