name: Release packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/*/CHANGELOG.md"
      - ".changeset/*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/ci-setup
          
      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun version-packages
          publish: bun publish-packages
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish release tags
        run: git push --follow-tags --set-upstream origin HEAD